---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: r2dbc/r2dbc-client

inputs:
- name: r2dbc-client
- name: r2dbc-postgresql-artifactory
- name: r2dbc-spi-artifactory

outputs:
- name: r2dbc-client-artifactory

caches:
- path: maven
- path: postgresql

run:
  path: r2dbc-client/ci/perm-patch.sh
  args:
  - r2dbc-client/ci/build.sh
